services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [ .:/usr/src/app ]
    ports: [ 4000:4000 ]
    environment: [JEKYLL_ENV=docker]
    user: 1000:1000
    command: jekyll serve --host 0.0.0.0 -w --config _config.yml,_config_docker.yml